name: K6 load test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v3

      - name: step 2 - Run K6 load test
        uses: grafana/k6-action@v0.6.0
        with:
          filename: scripts/test.js

      - run: ls & mkdir report & mv index.html report

      - name: step 4 - upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: relatorio de testes de perfomance
          path: report